p8105_hw1_jz3571
================
Junyan Zhu
2022-09-21

# Problem 1

## download and load library dataset

``` r
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
data("penguins", package = "palmerpenguins")
```

## Look at the data

### Important variables

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

There are 8 variables in total in the dataset of penguins describing
species, islands, bill length in mm, bill depth in mm, flipper length in
mm, body mass in g, sex and year.

### Size of dataset

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

There are 344 rows and 8 columes in the dataset

### Mean of flipper length

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

After dropping the two missing data, the mean of flppper length in mm is
about 200.9.

## Scatterplot of flipper length and bill length

### Make the scatterplot

``` r
ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_jz3571_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

``` r
ggp = ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

### Save the scatterplot

``` r
ggsave(filename = "scatterplot_of_penguins.pdf", plot = ggp)
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

## Creat a data frame

``` r
samp_df = tibble (
  var_num = rnorm(10, mean = 0, sd = 1),
  var_logic = var_num > 0,
  var_vector = c("a","b","c",'d','e','f','g','h','i','j'),
  var_factor = factor(c("1", "2", "3",'1','2','3','1','2','3','1'))
)
```

## Mean of each variable

``` r
#mean of numeric variable
mean(samp_df$var_num)
```

    ## [1] 0.1597465

``` r
#mean of logical variable
mean(samp_df$var_logic)
```

    ## [1] 0.5

``` r
#mean of character variable
mean(samp_df$var_vector)
```

    ## Warning in mean.default(samp_df$var_vector): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
#mean of factor variable
mean(samp_df$var_factor)
```

    ## Warning in mean.default(samp_df$var_factor): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

We can get a mean from numerical and logcial variable respectively, but
we cannot take means form character and factor variable

## Apply \`as.numeric

\`

``` r
#mean of logical variable
mean(as.numeric(samp_df$var_logic))
#mean of character variable
mean(as.numeric(samp_df$var_vector))
```

    ## Warning in mean(as.numeric(samp_df$var_vector)): NAs introduced by coercion

``` r
#mean of factor variable
mean(as.numeric(samp_df$var_factor))
```

Now we can get a mean from logical and factor variable, but still cannot
from the character variable. This is because we can only get a mean from
numerical values. In this case, the factor variable is converted to
numerical variable based on its level, while for character variable such
convertion is unable to made.
